### ISSUE TITLE
JSON Patch & Hal Links

### ISSUE THREAD

**Issue by maennchen** [mikekelly/hal-rfc#12]
How should JSON Patches (RFC 6902) look like for relations?

Example:

Post HAL Resource:

``` json
{
  "_links": {
    "author": {
      "href": "/users/7"
    }
  },
  "title": "Some Title"
}
```

If I want to change the `author` of the resource, what JSON PATCH should I send?

Am I on the wrong path with my question and for example [LINK](https://tools.ietf.org/html/draft-snell-link-method-01) should be used? (Which does feel strange since all the links are included in the body normally.)

**Comment by maennchen** [comment]
Current `application/json-patch+json`:

```json
[
  {
    "op": "replace",
    "path": "/_links/author/href",
    "value": "/users/42"
  }
]
```

**Comment by C06A** [comment]
> JSON Patches (RFC 6902)

Interesting idea. Just keep in mind that this spec doesn't defined any format of the body to submit to POST, PUT, PATCH, etc. HTTP methods. Your suggestion can be used by API designer, but don't need to be referenced in the current state of this spec.

Also keep in mind that HAL resource is not the server side resource. It is just a representation of such. So while designing the specific API one doesn't need to update JSON, but server resource instead.

Now to specifics of your question: API may use self link's href to reference resource during single session. Between sessions (persisted on the client side) I wouldn't recommend to use it, because server may change the URLs between sessions (upgraded). Instead I added to the API definition the additional attribute holding the persistable reference to the resource, so the client may persist it locally and recall resource later. For this to make sense server should promise to keep support to accept old formats in the future.
